cloudscale-ch/acceptance-tests

README.md
resources.py
test_floating_ip.py

Previously, the limit was set to ten - a limit which we did not yet verify using acceptance tests.

Ensure up to sixteen Floating IPs can be assigned to a server

---

constants.py
resources.py
util.py

Some images (FCOS, Flatcar) automatically update themselves when they are first
booted. Ab update service will update and then reboot the host, causing an
extra boot cycle that is not present on other images.
We have worked around the issue before, by expecting a certain unstableness in
our SSH connections, but there is a non-deterministic element to these images
that we would like to avoid entirely.
This commit ensures that for those special images, the update services are
masked before the first boot, making them behave more like our default images.
Fixes #1.

Disable automatic updates on selected images

---

README.md
api.py
constants.py
tasks.py
test_api.py
util.py

This adds a new test module to test basic API functionality. It implements 4 tests in this module to check various aspects of the HTTP response headers. More tests for other aspects of the API can be added later.

Check API response headers

---

README.md
events.py
resources.py
test_server.py
util.py

This merge request fixes two issues that were discovered with Debian 11, but could occur on other images as well:
1. Before reconnecting to a server after reboot, we need to wait for the server to actually power off.
2. The `dmidecode` utility should not be a requirement to calculate the present memory.
I've ran the updated tests against all images and against Debian 11 as a default.

Fix issues found testing Debian 11

---

.github/workflows/acceptance-tests-in-lpg1.yml
.github/workflows/acceptance-tests-in-rma1.yml

It looks like GitHub is now able to schedule those tests quite accurately, when
in the past it was largely random.

Move the regular tests closer to our office hours

---

api.py
conftest.py

This makes it easier for us to detect those requests in the backend.

Use a unique agent string for requests generated by Acceptance Tests

---

resources.py

The assumption when writing tests was that ping would block for the given amount
of time, then retry. Where this assumption was violated, the tests would sometimes
fail randomly, as the wait was not long enough.

Ensure ping function calls last as long as expected

---

util.py

The jump host was not retried properly if it wasn't ready. This lead to more test failures as our use of jump-hosts increased.

Fix a rare connection issue when connecting through a jump-host

---

conftest.py
test_custom_image.py

Add tests in order to test custom images using UEFI firmware type.
- Upload an image with firmware_type=uefi
- Create a server using the uploaded UEFI image
For more information, see [cloudscale.ch List Custom Images API Docs](https://www.cloudscale.ch/en/api/v1#custom-images) --> `firmware_type`.

Add test to deploy UEFI images and UEFI server

---

constants.py

The new `flatcar-stable` slug does not change anymore, when a new release is out.

Support the new flatcar-stable slug

---

conftest.py

This image currently fails regularly, but randomly when being tested. These failures have no bearing on the functioning of our cloud. Since we do watch our acceptance tests closely for regressions found there, we disable these tests, as we investigate further, to avoid noise in our monitoring.

Disable FCOS image testing for the time being

---

test_floating_ip.py
test_private_network.py

As discussed, these adjustments should cause a known false positive to disappear, and a known false negative to appear (should the issue arise).

Adjust private network and Floating IP stability timings

---

.github/workflows/acceptance-tests-in-rma1.yml

This avoids overlapping tests. Those are less than ideal, as they may skew our timings.

Start tests in prod-rma1 earlier

---

conftest.py
constants.py
test_public_network.py

Includes the following changes:
* Launch more servers to find two matching servers.
* Launch them less aggressively (mostly serialized on the API anyway).
* Do not fail if a server cannot be launched, unless all servers fail.
* Use launch parameters that are easy to adjust in the future.
This also includes the doc change from the reverted merge.

Increase robustness of two_servers_in_same_subnet

---

test_private_network.py

This timeout has been increased in the past as we were struggling with some scaling issues in the backend. This has been fixed and we should now be able to use a much lower timeout.

Lower the timeout for test_private_network_attach_later

---

README.md
events.py
resources.py
test_private_network.py

This ensures we do not send any domain search options:
- `option domain-search`
- `option dhcp6.domain-search`
See `man dhcp-options`.
It also asserts that updates to the DNS servers of the subnet, are reflected in the DHCP replies shortly after.

Test DHCP replies related to DNS settings

---

README.md
api.py
resources.py
test_floating_ip.py
util.py

This ensures that moving a large number of Floating IPs in one go propagates in a reasonable amount of time.

Add Floating IP mass reassignment tests

---

test_floating_ip.py

The time it takes is slightly longer than anticipated. However, the goal
we initially set was also meant for fewer IPs, so we switch to that.

Increase time for mass-failover-timings

---

.github/workflows/acceptance-tests-in-lpg1.yml
.github/workflows/acceptance-tests-in-rma1.yml
.github/workflows/custom-acceptance-test.yml
.github/workflows/implemented-tests-table.yml
.github/workflows/linting.yml
.github/workflows/run-acceptance-tests.yml
conftest.py
events.py
pytest
requirements.txt

This introduces a number of improvements for our acceptance tests:
1. We get rid of GitHub warnings on the action view.
2. We can now run manual tests without influencing scheduled tests.
3. We can now run only certain tests manually (e.g., to verify a new test in a branch).
4. Rerun errors are no longer hidden and tests that just failed are now retried towards the end.
5. The events log now contains the line that caused the error, and the exception, for future reporting.

Improve the way we execute tests

---

.github/workflows/run-acceptance-tests.yml
conftest.py
events.py
pytest
tasks.py
util.py

This ensures that we have something useful for each GitHub invocation.
See the following run for an example:
https://github.com/cloudscale-ch/acceptance-tests/actions/runs/7915887754
Since this and other runs did complete successfully, here's an example of a local failed run:
https://gist.github.com/href/0c600af5ed6f0bc3cc817a16a83f4fc7
Note: You can click on the errors to get the full traceback.

Print a summary after each test execution

---

test_floating_ip.py

This is not the performance we are aiming for, so we have created an internal ticket to be able to get back to 30s. For now however, 30s is not feasible at all times.

Inrease mass-failover timeout from 30s to 40s

---

resources.py

This prevents the test case from continuing on states such as `'failed'` which enables clearer test error messages.

Improve Status Checking Of Custom Image Import

---

resources.py

Using the log, this allows us to find out how many times each invocation tries until it is able to ping the API via IPv6:
```bash
cat events/*.log \
| egrep 'ping.+2a06' \
| jq -r '.worker + " " + .time + " " + .test + " " + .command + " exit_status=" + (.exit_status | tostring)' \
| sort -k 1,2 \
| awk '{print $0} /exit_status=0/ { printf "\n" }'
```

Try IPv6 ping longer and more often

---

resources.py

We wait between probes, to ensure that the behavior matches our expectations. This adds an extra delay to some tests, but this should happen in less than 99.9% of the cases.

Send two ICMPv6 probes, each time we start a server

---

README.md
resources.py
test_nested_virtualization.py

Test if KVM virtualization works with QEMU.

Add nested virtualization tests

---

api.py
events.py
tasks.py

- We do not want to retry on HTTP 400, unless it is a DELETE.
- We want to log the retries with the corresponding request.

Scope retries more clearly

---

tasks.py
test_infrastructure.py

Add tests to verify port 25 outgoing is blocked by default.

Add port 25 block tests

---

api.py
events.py

Log the request body to the event log for failed requests. This often contains a more detailed error message. Successful request bodies are not logged. They may contain sensitive information and are generally much larger.
This removes the "print" logging which was done before. This was the only part of the code which logged using print to standard output.

Log request body for failed requests
